parameters:
    mango_api.class: '\MangoPay\MangoPayApi'
    part_fire_mango_pay.dto.user_translator.class: '\PartFire\MangoPayBundle\Models\DTOs\Translators\UserTranslator'

services:
    part_fire_mango_pay.models_adapters.user_query:
        class: PartFire\MangoPayBundle\Models\Adapters\UserQuery
        arguments: ['%mango_api.class%', '@monolog.logger_prototype', '%part_fire_mango_pay.dto.user_translator.class%']

    part_fire_mango_pay.services.user:
        class: PartFire\MangoPayBundle\Services\User
        arguments: ['@part_fire_mango_pay.models_adapters.user_query']