parameters:
    part_fire_mango_pay.dto.user_translator.class: 'PartFire\MangoPayBundle\Models\DTOs\Translators\UserTranslator'
    part_fire_mango_pay.dto.wallet_translator.class: 'PartFire\MangoPayBundle\Models\DTOs\Translators\WalletTranslator'
    part_fire_mango_pay.dto.kyc_document_translator.class: 'PartFire\MangoPayBundle\Models\DTOs\Translators\KycDocumentTranslator'
    part_fire_mango_pay.dto.kyc_document_page_translator.class: 'PartFire\MangoPayBundle\Models\DTOs\Translators\KycDocumentPageTranslator'
    part_fire_mango_pay.dto.transfer_translator.class: 'PartFire\MangoPayBundle\Models\DTOs\Translators\TransferTranslator'
    part_fire_mango_pay.dto.card_translator.class: 'PartFire\MangoPayBundle\Models\DTOs\Translators\CardTranslator'
    part_fire_mango_pay.dto.payin_translator.class: 'PartFire\MangoPayBundle\Models\DTOs\Translators\PayInTranslator'
    part_fire_mango_pay.dto.bankaccount_translator.class: 'PartFire\MangoPayBundle\Models\DTOs\Translators\BankAccountTranslator'
    part_fire_mango_pay.dto.payout_translator.class: 'PartFire\MangoPayBundle\Models\DTOs\Translators\PayOutTranslator'

services:
    part_fire_mango_pay.factory_repo:
        class: PartFire\MangoPayBundle\Entity\Repository\MangoPayRepositoryFactory
        arguments: ['@doctrine.orm.default_entity_manager']

    part_fire_mango_pay.vendor_mango_api:
        class: MangoPay\MangoPayApi

    part_fire_mango_pay.models_dtos_translators.user_translator:
        class: '%part_fire_mango_pay.dto.user_translator.class%'

    part_fire_mango_pay.models_dtos_translators.wallet_translator:
        class: '%part_fire_mango_pay.dto.wallet_translator.class%'

    part_fire_mango_pay.models_dtos_translators.kyc_document_translator:
        class: '%part_fire_mango_pay.dto.kyc_document_translator.class%'

    part_fire_mango_pay.models_dtos_translators.kyc_document_page_translator:
        class: '%part_fire_mango_pay.dto.kyc_document_page_translator.class%'

    part_fire_mango_pay.models_dtos_translators.transfer_translator:
        class: '%part_fire_mango_pay.dto.transfer_translator.class%'

    part_fire_mango_pay.models_dtos_translators.card_translator:
        class: '%part_fire_mango_pay.dto.card_translator.class%'

    part_fire_mango_pay.models_dtos_translators.payin_translator:
        class: '%part_fire_mango_pay.dto.payin_translator.class%'

    part_fire_mango_pay.models_dtos_translators.bankaccount_translator:
        class: '%part_fire_mango_pay.dto.bankaccount_translator.class%'

    part_fire_mango_pay.models_dtos_translators.payout_translator:
        class: '%part_fire_mango_pay.dto.payout_translator.class%'

    part_fire_mango_pay.models_adapters.user_query:
        class: PartFire\MangoPayBundle\Models\Adapters\UserQuery
        arguments:
            - '%mangopay_client_id%'
            - '%mangopay_client_password%'
            - '%mangopay_base_url%'
            - '@part_fire_mango_pay.vendor_mango_api'
            - '@logger'
            - '@part_fire_mango_pay.models_dtos_translators.user_translator'

    part_fire_mango_pay.models_adapters.wallet_query:
        class: PartFire\MangoPayBundle\Models\Adapters\WalletQuery
        arguments:
            - '%mangopay_client_id%'
            - '%mangopay_client_password%'
            - '%mangopay_base_url%'
            - '@part_fire_mango_pay.vendor_mango_api'
            - '@logger'
            - '@part_fire_mango_pay.models_dtos_translators.wallet_translator'

    part_fire_mango_pay.models_adapters.kyc_document_query:
        class: PartFire\MangoPayBundle\Models\Adapters\KycDocumentQuery
        arguments:
            - '%mangopay_client_id%'
            - '%mangopay_client_password%'
            - '%mangopay_base_url%'
            - '@part_fire_mango_pay.vendor_mango_api'
            - '@logger'
            - '@part_fire_mango_pay.models_dtos_translators.kyc_document_translator'

    part_fire_mango_pay.models_adapters.kyc_document_page_query:
        class: PartFire\MangoPayBundle\Models\Adapters\KycDocumentPageQuery
        arguments:
            - '%mangopay_client_id%'
            - '%mangopay_client_password%'
            - '%mangopay_base_url%'
            - '@part_fire_mango_pay.vendor_mango_api'
            - '@logger'
            - '@part_fire_mango_pay.models_dtos_translators.kyc_document_page_translator'

    part_fire_mango_pay.models_adapters.transfer_query:
        class: PartFire\MangoPayBundle\Models\Adapters\TransferQuery
        arguments:
            - '%mangopay_client_id%'
            - '%mangopay_client_password%'
            - '%mangopay_base_url%'
            - '@part_fire_mango_pay.vendor_mango_api'
            - '@logger'
            - '@part_fire_mango_pay.models_dtos_translators.transfer_translator'

    part_fire_mango_pay.models_adapters.hook_query:
        class: PartFire\MangoPayBundle\Models\Adapters\HookQuery
        arguments:
            - '%mangopay_client_id%'
            - '%mangopay_client_password%'
            - '%mangopay_base_url%'
            - '@part_fire_mango_pay.vendor_mango_api'
            - '@logger'

    part_fire_mango_pay.models_adapters.cardregistrations_query:
        class: PartFire\MangoPayBundle\Models\Adapters\CardRegistrationsQuery
        arguments:
            - '%mangopay_client_id%'
            - '%mangopay_client_password%'
            - '%mangopay_base_url%'
            - '@part_fire_mango_pay.vendor_mango_api'
            - '@logger'
            - '@part_fire_mango_pay.models_dtos_translators.card_translator'

    part_fire_mango_pay.models_adapters.card_query:
        class: PartFire\MangoPayBundle\Models\Adapters\CardQuery
        arguments:
            - '%mangopay_client_id%'
            - '%mangopay_client_password%'
            - '%mangopay_base_url%'
            - '@part_fire_mango_pay.vendor_mango_api'
            - '@logger'
            - '@part_fire_mango_pay.models_dtos_translators.card_translator'

    part_fire_mango_pay.models_adapters.payin_query:
        class: PartFire\MangoPayBundle\Models\Adapters\PayInQuery
        arguments:
            - '%mangopay_client_id%'
            - '%mangopay_client_password%'
            - '%mangopay_base_url%'
            - '@part_fire_mango_pay.vendor_mango_api'
            - '@logger'
            - '@part_fire_mango_pay.models_dtos_translators.payin_translator'

    part_fire_mango_pay.models_adapters.bankaccount_query:
            class: PartFire\MangoPayBundle\Models\Adapters\BankAccountQuery
            arguments:
                - '%mangopay_client_id%'
                - '%mangopay_client_password%'
                - '%mangopay_base_url%'
                - '@part_fire_mango_pay.vendor_mango_api'
                - '@logger'
                - '@part_fire_mango_pay.models_dtos_translators.bankaccount_translator'

    part_fire_mango_pay.models_adapters.payout_query:
            class: PartFire\MangoPayBundle\Models\Adapters\PayOutQuery
            arguments:
                - '%mangopay_client_id%'
                - '%mangopay_client_password%'
                - '%mangopay_base_url%'
                - '@part_fire_mango_pay.vendor_mango_api'
                - '@logger'
                - '@part_fire_mango_pay.models_dtos_translators.payout_translator'

    part_fire_mango_pay.services.user:
        class: PartFire\MangoPayBundle\Services\User
        arguments: ['@part_fire_mango_pay.models_adapters.user_query']

    part_fire_mango_pay.services.wallet:
        class: PartFire\MangoPayBundle\Services\Wallet
        arguments: ['@part_fire_mango_pay.models_adapters.wallet_query']

    part_fire_mango_pay.services.card:
        class: PartFire\MangoPayBundle\Services\Card
        arguments:
            - '@part_fire_mango_pay.models_adapters.cardregistrations_query'
            - '@part_fire_mango_pay.models_adapters.card_query'

    part_fire_mango_pay.services.payin:
        class: PartFire\MangoPayBundle\Services\PayIn
        arguments: ['@part_fire_mango_pay.models_adapters.payin_query']

    part_fire_mango_pay.services.hook:
        class: PartFire\MangoPayBundle\Services\Hook
        arguments: ['@part_fire_mango_pay.models_adapters.hook_query']

    part_fire_mango_pay.services.kyc:
        class: PartFire\MangoPayBundle\Services\Kyc
        arguments:
            - '@part_fire_mango_pay.models_adapters.kyc_document_query'
            - '@part_fire_mango_pay.models_adapters.kyc_document_page_query'

    part_fire_mango_pay.services.transfer:
        class: PartFire\MangoPayBundle\Services\Transfer
        arguments: ['@part_fire_mango_pay.models_adapters.transfer_query']

    part_fire_mango_pay.services.webhook:
        class: PartFire\MangoPayBundle\Services\HookHandleService
        arguments:
            - '@part_fire_mango_pay.factory_repo'
            - '@part_fire_slack_service'
            - '@event_dispatcher'
            - '@part_fire_mango_pay.services.payin'
            - '@part_fire_mango_pay.services.payout'
            - '@part_fire_mango_pay.services.transfer'
            - '@part_fire_mango_pay.services.kyc'
            - '%kernel.environment%'

    part_fire_mango_pay.services.bank_account:
        class: PartFire\MangoPayBundle\Services\BankAccounts
        arguments: ['@part_fire_mango_pay.models_adapters.bankaccount_query']

    part_fire_mango_pay.services.payout:
        class: PartFire\MangoPayBundle\Services\PayOut
        arguments: ['@part_fire_mango_pay.models_adapters.payout_query']

